vim.opt.termguicolors = true
vim.opt.cursorline = true
vim.opt.winblend = 0
vim.opt.wildoptions = 'pum'
vim.opt.pumblend = 5
vim.o.background = 'dark'
-- vim.opt.background = 'light'
-- vim.o.background = 'light'
--vim.api.nvim_set_hl(0, 'LineNr', { fg = '#777777' })
